/*
################################################################################
# Copyright 2019 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################
*/
export const UPLOAD_CONFIG = 'UPLOAD_CONFIG'
export const UPLOAD_CONFIG_SUCCESS = 'UPLOAD_CONFIG_SUCCESS'
export const UPLOAD_CONFIG_FAILURE = 'UPLOAD_CONFIG_FAILURE'
export const UPLOAD_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'UPLOAD_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const CONFIG = 'CONFIG'
export const FETCH_CONFIG = "FETCH_CONFIG"
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS'
export const FETCH_CONFIG_FAILURE = 'FETCH_CONFIG_FAILURE'
export const FETCH_CONFIG_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'FETCH_CONFIG_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const UPDATE_CONFIG = 'UPDATE_CONFIG'

export const CONFIG_CONFIG_NAME = 'CONFIG_CONFIG_NAME'
export const FETCH_CONFIG_CONFIG_NAME = "FETCH_CONFIG_CONFIG_NAME"
export const FETCH_CONFIG_CONFIG_NAME_SUCCESS = 'FETCH_CONFIG_CONFIG_NAME_SUCCESS'
export const FETCH_CONFIG_CONFIG_NAME_FAILURE = 'FETCH_CONFIG_CONFIG_NAME_FAILURE'
export const FETCH_CONFIG_CONFIG_NAME_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'FETCH_CONFIG_CONFIG_NAME_IN_PROGRESS',
    ERROR: 'ERROR'
}


export const UIMETADATA = 'UIMETADATA'
export const UIMETADATA_FETCH = "UIMETADATA_FETCH"
export const UIMETADATA_FETCH_SUCCESS = 'UIMETADATA_FETCH_SUCCESS'
export const UIMETADATA_FETCH_FAILURE = 'UIMETADATA_FETCH_FAILURE'
export const UIMETADATA_FETCH_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'UIMETADATA_FETCH_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const UIMETADATA_PREVIOUS = 'UIMETADATA_PREVIOUS'
export const UIMETADATA_FETCH_PREVIOUS = "UIMETADATA_FETCH_PREVIOUS"
export const UIMETADATA_FETCH_PREVIOUS_SUCCESS = 'UIMETADATA_FETCH_PREVIOUS_SUCCESS'
export const UIMETADATA_FETCH_PREVIOUS_FAILURE = 'UIMETADATA_FETCH_PREVIOUS_FAILURE'
export const UIMETADATA_FETCH_PREVIOUS_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'UIMETADATA_FETCH_PREVIOUS_IN_PROGRESS',
    ERROR: 'ERROR'
}
export const UIMETADATA_UPDATE_SELECTED_CONFIG = 'UIMETADATA_UPDATE_SELECTED_CONFIG'
export const UIMETADATA_UPDATE = 'UIMETADATA_UPDATE'

export const UIMETADATA_CONFIGS = 'UIMETADAT_CONFIGS'
export const UIMETADATA_CONFIGS_FETCH = "UIMETADATA_CONFIGS_FETCH"
export const UIMETADATA_CONFIGS_FETCH_SUCCESS = 'UIMETADATA_CONFIGS_FETCH_SUCCESS'
export const UIMETADATA_CONFIGS_FETCH_FAILURE = 'UIMETADATA_CONFIGS_FETCH_FAILURE'
export const UIMETADATA_CONFIGS_FETCH_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'UIMETADATA_CONFIGS_FETCH_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const UIMETADATA_ALL_CONFIGS_NAMES = 'UIMETADAT_ALL_CONFIGS_NAMES'
export const UIMETADATA_ALL_CONFIGS_NAMES_FETCH = "UIMETADATA_ALL_CONFIGS_NAMES_FETCH"
export const UIMETADATA_ALL_CONFIGS_NAMES_FETCH_SUCCESS = 'UIMETADATA_ALL_CONFIGS_NAMES_FETCH_SUCCESS'
export const UIMETADATA_ALL_CONFIGS_NAMES_FETCH_FAILURE = 'UIMETADATA_ALL_CONFIGS_NAMES_FETCH_FAILURE'
export const UIMETADATA_ALL_CONFIGS_NAMES_FETCH_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'UIMETADATA_ALL_CONFIGS_NAMES_FETCH_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const CONFIG_ABOUT = 'CONFIG_ABOUT'
export const FETCH_CONFIG_ABOUT = "FETCH_CONFIG_ABOUT"
export const FETCH_CONFIG_ABOUT_SUCCESS = 'FETCH_CONFIG_ABOUT_SUCCESS'
export const FETCH_CONFIG_ABOUT_FAILURE = 'FETCH_CONFIG_ABOUT_FAILURE'
export const FETCH_CONFIG_ABOUT_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'FETCH_CONFIG_ABOUT_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const VALIDATE_CONFIG = 'VALIDATE_CONFIG'
export const VALIDATE_CONFIG_SUCCESS = 'VALIDATE_CONFIG_SUCCESS'
export const VALIDATE_CONFIG_FAILURE = 'VALIDATE_CONFIG_FAILURE'
export const VALIDATE_REQUEST_STATUS = {
    DONE: 'DONE',
    DONE_WITH_WARNING: 'DONE_WITH_WARNING',
    IN_PROGRESS: 'VALIDATE_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const DEPLOYMENT_AUTHORIZED = "DEPLOYMENT_AUTHORIZED"
export const DEPLOYMENT_START = 'DEPLOYMENT_START'
export const DEPLOYMENT_SUCCESS = 'DEPLOYMENT_SUCCESS'
export const DEPLOYMENT_FAILURE = 'DEPLOYMENT_FAILURE'
export const DEPLOYMENT_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'DEPLOYMENT_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const DEPLOYMENT_IS_RUNNING = "DEPLOYMENT_IS_RUNNING"
export const DEPLOYMENT_RUNNING = 'DEPLOYMENT_RUNNING'
export const DEPLOYMENT_RUNNING_SUCCESS = 'DEPLOYMENT_RUNNING_SUCCESS'
export const DEPLOYMENT_RUNNING_FAILURE = 'DEPLOYMENT_RUNNING_FAILURE'
export const DEPLOYMENT_RUNNING_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'DEPLOYMENT_RUNNING_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const GENERATE_CONFIG = 'GENERATE_CONFIG'
export const GENERATE_CONFIG_SUCCESS = 'GENERATE_CONFIG_SUCCESS'
export const GENERATE_CONFIG_FAILURE = 'GENERATE_CONFIG_FAILURE'
export const GENERATE_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'GENERATE_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const STATES_REFRESH_DATE = "STATES_REFRESH_DATE"
export const STATES_FETCH = "STATES_FETCH"
export const STATES_FETCH_SUCCESS = 'STATES_FETCH_SUCCESS'
export const STATES_FETCH_FAILURE = 'STATES_FETCH_FAILURE'
export const STATES_FETCH_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'STATES_FETCH_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const STATES_FETCH_EXTENSIONS = "STATES_FETCH_EXTENSIONS"
export const STATES_FETCH_EXTENSIONS_SUCCESS = 'STATES_FETCH_EXTENSIONS_SUCCESS'
export const STATES_FETCH_EXTENSIONS_FAILURE = 'STATES_FETCH_EXTENSIONS_FAILURE'
export const STATES_FETCH_EXTENSIONS_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'STATES_FETCH_EXTENSIONS_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const STATES_INSERT = "STATES_INSERT"
export const STATES_INSERT_SUCCESS = 'STATES_INSERT_SUCCESS'
export const STATES_INSERT_FAILURE = 'STATES_INSERT_FAILURE'
export const STATES_INSERT_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'STATES_INSERT_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const STATES_DELETE = "STATES_DELETE"
export const STATES_DELETE_SUCCESS = 'STATES_DELETE_SUCCESS'
export const STATES_DELETE_FAILURE = 'STATES_DELETE_FAILURE'
export const STATES_DELETE_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'STATES_DELETE_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const ENGINE_RESET = "ENGINE_RESET"
export const ENGINE_RESET_SUCCESS = 'ENGINE_RESET_SUCCESS'
export const ENGINE_RESET_FAILURE = 'ENGINE_RESET_FAILURE'
export const ENGINE_RESET_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'ENGINE_RESET_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const SETTINGS_SAVE = "SETTINGS_SAVE"

export const LOGS_REFRESH_DATE = "LOGS_REFRESH_DATE"
export const LOGS_SAVE_PARAMETERS = "LOGS_SAVE_PARAMETERS"
export const LOGS_UPDATE = "LOGS_UPDATE"
export const LOGS_FETCH = "LOGS_FETCH"
export const LOGS_FETCH_SUCCESS = 'LOGS_FETCH_SUCCESS'
export const LOGS_FETCH_FAILURE = 'LOGS_FETCH_FAILURE'
export const LOGS_FETCH_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'LOGS_FETCH_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const CR_CHECK_STATUS = "CR_CHECK_STATUS"
export const CR_CHECK_STATUS_SUCCESS = 'CR_CHECK_STATUS_SUCCESS'
export const CR_CHECK_STATUS_FAILURE = 'CR_CHECK_STATUS_FAILURE'
export const CR_CHECK_STATUS_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'CR_CHECK_STATUS_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const CR_FETCH_SETTINGS = "CR_FETCH_SETTINGS"
export const CR_FETCH_SETTINGS_SUCCESS = 'CR_FETCH_SETTINGS_SUCCESS'
export const CR_FETCH_SETTINGS_FAILURE = 'CR_FETCH_SETTINGS_FAILURE'
export const CR_FETCH_SETTINGS_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'CR_FETCH_SETTINGS_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const MODAL_UPDATE = 'MODAL_UPDATE'

export const STATE_SET_STATUS = "STATE_SET_STATUS"
export const STATE_SET_STATUS_SUCCESS = 'STATE_SET_STATUS_SUCCESS'
export const STATE_SET_STATUS_FAILURE = 'STATE_SET_STATUS_FAILURE'
export const STATE_SET_STATUS_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'STATE_SET_STATUS_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const EXTENSIONS_LOADING = 'EXTENSIONS_LOADING'
export const EXTENSIONS_REGISTERED = 'EXTENSIONS_REGISTERED'
export const EXTENSIONS_FETCH_REGISTERED = "EXTENSIONS_FETCH_REGISTERED"
export const EXTENSIONS_FETCH_REGISTERED_SUCCESS = 'EXTENSIONS_FETCH_REGISTERED_SUCCESS'
export const EXTENSIONS_FETCH_REGISTERED_FAILURE = 'EXTENSIONS_FETCH_REGISTERED_FAILURE'
export const EXTENSIONS_FETCH_REGISTERED_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'EXTENSIONS_FETCH_REGISTERED_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const EXTENSIONS_ALL = 'EXTENSIONS_ALL'
export const EXTENSIONS_FETCH_ALL = "EXTENSIONS_FETCH_ALL"
export const EXTENSIONS_FETCH_ALL_SUCCESS = 'EXTENSIONS_FETCH_ALL_SUCCESS'
export const EXTENSIONS_FETCH_ALL_FAILURE = 'EXTENSIONS_FETCH_ALL_FAILURE'
export const EXTENSIONS_FETCH_ALL_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'EXTENSIONS_FETCH_ALL_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const EXTENSION_REGISTER = "EXTENSION_REGISTER"
export const EXTENSION_REGISTER_SUCCESS = 'EXTENSION_REGISTER_SUCCESS'
export const EXTENSION_REGISTER_FAILURE = 'EXTENSION_REGISTER_FAILURE'
export const EXTENSION_REGISTER_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'EXTENSION_REGISTERED_IN_PROGRESS',
    ERROR: 'ERROR'
}

export const EXTENSION_UNREGISTER = "EXTENSION_UNREGISTER"
export const EXTENSION_UNREGISTER_SUCCESS = 'EXTENSION_UNREGISTER_SUCCESS'
export const EXTENSION_UNREGISTER_FAILURE = 'EXTENSION_UNREGISTER_FAILURE'
export const EXTENSION_UNREGISTER_REQUEST_STATUS = {
    DONE: 'DONE',
    IN_PROGRESS: 'EXTENSION_UNREGISTERED_IN_PROGRESS',
    ERROR: 'ERROR'
}
